config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users
  resources :posts
  get 'home/index'

  root to: "home#index"
  resources :channels
  resources :posts do
    member do
      get 'upvote'
      get 'downvote'
    end
    resources :comments
      member do
        get 'upvote'
        get 'downvote'
      end
  end
 

  resources :comments do
    member do
      get 'upvote'
      get 'downvote'
    end
    resources :comments
    #member do
    #   get 'upvote'
    #   get 'downvote'
    # end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	acts_as_votable
	belongs_to :commentable, polymorphic: true
	belongs_to :user
	has_many :comments, as: :commentable, dependent: :destroy
	validates :text, presence: true
	validates :user_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	#before_action :get_post
  before_action :authenticate_user!
	before_action :get_comment, only: [:destroy, :upvote, :downvote, :update, :edit]
	before_action :find_commentable
    #before_action :authenticate_admin!, only: [:destroy]
	def create
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user

    if @comment.save
      @comment.upvote_from(current_user)
      respond_to do |format|
        format.html do
          	flash[:success] = 'Comment posted.'
          	redirect_to :back
        end
        format.js # JavaScript response
      end      
    else
      redirect_to :back, notice: "Your comment wasn't posted!"
    end
  end

  def edit
  end



  def update
      if current_user == @comment.user and @comment.update(comment_edit_params)
        format.html { redirect_to @comment.post, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end    
  end

  def upvote
    @comment.upvote_from(current_user)
    respond_to do |format|
      format.html do
        flash[:success] = 'Comment liked.'
          redirect_to :back
        end
      format.js # JavaScript response
    end 
  end

  def downvote
    @comment.downvote_from(current_user)
    respond_to do |format|
      format.html do
        flash[:success] = 'Comment disliked.'
          redirect_to :back
        end
      format.js # JavaScript response
    end 
  end

	def destroy
		@comment.destroy
		respond_to do |format|
      		format.html do
        		flash[:success] = 'Comment deleted.'
        		redirect_to :back
      		end
      		format.js # JavaScript response
    	end
	end

	private
	def get_post
		@post = Post.find(params[:post_id])
	end

	def get_comment
		@comment = Comment.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit( :text)
	end
	def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Post.find(params[:post_id]) if params[:post_id]
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id = <%= "comment_#{comment.id}" %> style="list-style: none;" >

	<div class="comments_container" id="4e2402e14f48" style="margin-left:0px">
	<div id = <%= "comment_score_#{comment.id}"%>>
		<%= render 'comments/scores', comment: comment %>
	</div>
	
		<div>
			<div class="comments_info_container">
			<%= link_to comment.user.username, profile_path(comment.user), style: "font-weight: bold", class:"comment-user" %>
			<%= time_ago_in_words comment.created_at %> ago
			</div>
			<div class="comment_body_container" style="padding-bottom:10px">
			<p><%= comment.text%></p>
			</div>
			<div id="comment_4e2402e14f48" class="comment_actions_container">
				<a href=<%=  "#comment-box-#{comment.id}" %> data-toggle="collapse" data-parent="#comments-accordion">reply</a>
			</div>
		</div>
	</div>

	<div class = "collapse comment-box" id = <%=  "comment-box-#{comment.id}"%> >
	<%= form_for [comment, Comment.new]  , class: "form-inline" , remote: true do  |f| %>
		<div class="form-group">
			<%= f.text_area :text, placeholder: 'Add a Reply' , class: "form-control", id: "comment_content", style:"height:200px"%>
		</div>

		<div class="form-group">
			<%=  submit_tag "Reply", :class => "btn btn-success green" , style:"margin-top:10px"%>
			<%= render 'comments/format_help', stuff: comment %>
		</div>

		
			
		


		<% end %>
	</div>
	<ul>
		<%= render comment.comments %>
	</ul>
</li>

app/views/comments/_comment_box.html.erb
<%= form_for [post, Comment.new], class: "form-inline comment-box" , remote: true do |f| %>
                <div class="form-group">
                    <%= f.text_area :text, placeholder: 'Add a comment...' , class: "form-control", id: "comment_content", style:"height:200px"%>
                </div>
                    
                <div class="form-group">
                    <%=  submit_tag "Submit", :class => "btn btn-success" , style:"margin-top:10px"%>
                    <%= render 'comments/format_help', stuff: post %>
                </div>


                    
                    
<%  end %>

app/views/comments/_comment_old.html.erb
<% if comment.id? %>
<li id = <%= "comment_#{comment.id}" %> style="list-style: none;" >

  <article class="row">

    <div class="col-md-10 col-sm-10">
      <div class="panel panel-default arrow left">
        <div class="panel-body">
          <header class="text-left">
          <div class="row">
          <div class = "col-md-10">
            <div class="comment-user"><i class="fa fa-user"></i> <%=comment.user.username%></div>
            <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> <%= time_ago_in_words comment.created_at %> ago</time>
            </div>
            <%= render "comments/scores", comment:comment %>
            </div>
            
          </header>
          <div class="comment-post">
            <p>
             <%= comment.text %>
           </p>
         </div>
         <div class="row">
         <% if user_signed_in? && (current_user.id == comment.user.id) %>
          <div class="col-md-6">
            <p class = "text-left"><%= link_to '', get_correct_path(comment), method: :delete, data: { confirm: 'Delete comment?'}, remote: true, class: 'glyphicon glyphicon-trash text-danger', id: "#{comment.id}_delete", title: 'Delete comment', rel: 'tooltip' %>
            </p>
          </div>
          <div class="col-md-6">
            <%  else %>
            <div class="col-md-6 col-md-offset-6">
              <% end %>
              <p class="text-right"><a href=<%=  "#comment-box-#{comment.id}" %> data-toggle="collapse" data-parent="#comments-accordion" ><i class="fa fa-reply"></i> Reply</a></p>
            </div>

          </div>

        </div>
      </div>
    </div>
  </article>
  <div class = "collapse comment-box" id = <%=  "comment-box-#{comment.id}"%> >
   <%= form_for [comment, Comment.new]  , class: "form-inline" , remote: true do  |f| %>
  <div class="form-group">
    <%= f.text_area :text, placeholder: 'Add a Reply' , class: "form-control", id: "comment_content"%>
  </div>

  <div class="form-group">
    <%=  submit_tag "Reply", :class => "btn btn-success green" %>
  </div>


  <% end %>
</div>
<ul>
  <%= render comment.comments %>
</ul>
</li>
<% end %>

app/views/comments/_format_help.html.erb
<a style="float:right" data-toggle="collapse" data-target= <%="#formatting_#{stuff.class.name + stuff.id.to_s}" %> >formatting help</a>
<div id= <%="formatting_#{stuff.class.name + stuff.id.to_s}"%> class="formatting collapse">
    <table border="1" cellpadding="10" style="border:1px solid #cccccc">
    <tbody><tr style="background-color: #bbbbbb">
    <td width="50%">you type</td>
    <td width="50%">you see</td>
    </tr>
    <tr>
    <td>[headcycle!](https://www.headcycle.com)</td>
    <td><a href="http://www.headcycle.com">headcycle!</a></td>
    </tr>

    <tr>
    <td>*italics*</td>
    <td><i>italics</i></td>
    </tr>

    <tr>
    <td>**bold**</td>
    <td><b>bold</b></td>
    </tr>

    <tr>
    <td>* item 1<br>* item 2<br>* item 3</td>
    <td>
        <ul>
            <li>item 1</li>
            <li>item 1</li>
            <li>item 1</li>
        </ul>
    </td>
    </tr>

    <tr>
    <td>
    &gt; Email-style angle brackets<br>
    &gt; are used for blockquotes.<br>
    <br>
    &gt; &gt; And, they can be nested.<br>
    <br>
    &gt; #### Headers in blockquotes<br>
    &gt;<br> 
    &gt; * You can quote a list.<br>
    &gt; * Etc.<br>
    </td>
    <td>
    <blockquote>
    Email-style angle brackets<br>
    are used for blockquotes.<br>
    <br>
    <blockquote>
    And, they can be nested.
    </blockquote>
    <br>
    <h4>Headers in blockquotes</h4>

    <ul>
    <li>You can quote a list.</li>
    <li>Etc.</li>
    </ul>
    </blockquote>
    </td>
    </tr>
    <tr>
    <td>```function test(){<br>
    alert('hi');<br>
    }```
    </td>
    <td>
    <code>
    function test(){<br>
    alert('hi');<br>
    }<br>
    </code>
    </td>
    </tr>
    <tr>
    <td>~~strikethrough~~
    </td>
    <td>
    <strike>strikethrough</strike>
    </td>
    </tr>
    <tr>
    <td>
super^script    
    </td>
    <td>
super<sup>script</sup>
    </td>
    </tr>

    <tr>
    <td>
==this is highlighted==
    </td>
    <td>
<mark>this is highlighted</mark>
    </td>
    </tr>


    <tr style="background-color: #bbbbbb">
    <td>
    using spoiler tags
    </td>
    <td>
    mouse over or touch the hidden text
    </td>
    </tr>
    <tr>
    <td valign="top">
    When they ==:fell in love== I wasn't surprised.
    <hr>
    When they ==:fell<br>
    in<br>
    love==<br>
    I wasn't surprised.
    <hr>
    <u>Please Note</u><br>
    Spoilers can be used in a sentence or span multiple lines, with some caveats:
    <ul>
    <li>The end <mark>==</mark> tag <b><u>must not</u></b> have spaces separating it from the end of the spoiler text</li>
    <li>Multiline spoilers <b><u>cannot have</u></b> more than one return between lines</li>
    </ul>
    <hr>
    ==:This is a spoiler<span style="background-color:red">&nbsp;</span>==
    <br><br>
    ==:This<br><span style="background-color:red">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><br>
    is<br><span style="background-color:red">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><br>
    a<br><span style="background-color:red">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><br>
    spoiler==
    </td>
    <td valign="top">
    When they <span class="spoiler" style="font-size:16px">fell in love</span> I wasn't surprised.
    <hr>
    When they <span class="spoiler" style="font-size:16px">fell<br>
    in<br>
    love</span><br>
    I wasn't surprised.
    <hr>
    <br><br><br><br><br><br><br>
    <hr>
    <div style="color:red"><span class="glyphicon glyphicon-ban-circle"></span> will not work</div>
    </td>
    </tr>
    </tbody></table>
</div>

app/views/comments/_scores.html.erb
<div class="votes_container" >
    <div style="text-align: center">
        <img src="/assets/up.png" alt="up" class="voteup" style="cursor: pointer">
    </div>
    <div class="vote_container">0</div>
    <div style="text-align: center">

        <img src="/assets/down.png" alt="down" class="votedown" style="cursor: pointer">

    </div>
</div>

<% upvote, downvote = '', ''%>
<% if user_signed_in? %>
<% upvote = " upvoted" if current_user.voted_up_on? comment %>
<% downvote = " downvoted" if current_user.voted_down_on? comment %>

<% end %>
<div class="text-center post-upvote">
    <%= link_to "", upvote_comment_path(comment.id), remote:true, 
    class: "fa fa-arrow-up upvote" + upvote , id: "comment_#{comment.id}_upvote", title: 'Upvote Comment', rel: 'tooltip'  %></div>
    <div class = "text-center post-average-score">
        <h3 class=<%= upvote + downvote %>>
            <%= comment.get_upvotes.size - comment.get_downvotes.size %>
        </h3>
    </div>
    <div class="text-center post-downvote">
        <%= link_to "", downvote_comment_path(comment.id), remote:true, 
        class: "fa fa-arrow-down downvote" +downvote, id: "comment_#{comment.id}_downvote", title: 'Upvote post', rel: 'tooltip'  %>
    </div>

app/views/comments/create.js.erb
var selector = "<%= if @comment.commentable.class == Post then  '#comments-all' else '#comment_' + @comment.commentable.id.to_s end %>";
console.log(selector);
$(selector).html("<%= if @comment.commentable.class == Post then  j render @comment.commentable.comments else  j render @comment.commentable end %>");

app/views/comments/destroy.js.erb
console.log("destroy");
$('#comment_<%= @comment.id %>').remove();

app/views/comments/downvote.js.erb
var selector = "#comment_score_<%= @comment.id %>"
$(selector).html("<%= j (render partial: 'comments/scores', locals: { comment: @comment} ) %>")

app/views/comments/upvote.js.erb
var selector = "#comment_score_<%= @comment.id %>"
$(selector).html("<%= j (render partial: 'comments/scores', locals: { comment: @comment} ) %>")