config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users
  resources :posts
  get 'home/index'

  root to: "home#index"
  resources :channels
  resources :posts do
    member do
      get 'upvote'
      get 'downvote'
    end
    resources :comments
      member do
        get 'upvote'
        get 'downvote'
      end
  end
 

  resources :comments do
    member do
      get 'upvote'
      get 'downvote'
    end
    resources :comments
    #member do
    #   get 'upvote'
    #   get 'downvote'
    # end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :channel
	has_many :comments, as: :commentable, dependent: :destroy
	validates :text, :channel_id , :presence => true
	acts_as_votable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, only: [:edit, :new, :update, :create, :destroy, :upvote, :downvote]
  layout "head"

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
      
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def upvote
    @post.upvote_from(current_user)
    respond_to do |format|
      format.html do
        flash[:success] = 'Post liked.'
          redirect_to :back
        end
      format.js # JavaScript response
    end 
  end

  def downvote
    @post.downvote_from(current_user)
    respond_to do |format|
      format.html do
        flash[:success] = 'Post disliked.'
          redirect_to :back
        end
      format.js # JavaScript response
    end 
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    channel = Channel.find_by(name: params[:post][:channel].downcase)
    @post.channel_id = channel.id if channel
    @post.user = current_user
    respond_to do |format|
      
      
      if @post.save && channel
        @post.upvote_from(current_user)
        
        format.html { 
          redirect_to @post, notice: 'Post was successfully created.' 
        }
        format.json {
         render :show, status: :created, location: @post 
       }
      else
        if !channel
          @post.errors[:base] << "The channel #{params[:post][:channel]} doesn't exist"
        end
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_edit_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def get_channels
      @channels = Channel.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :text )
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_edit_params
      params.require(:post).permit(:text)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :url %>
    <%= f.input :text %>
    <%= f.input :channel %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_scores.html.erb
                <% upvote, downvote = '', ''%>
              <% if user_signed_in? %>
               <% upvote = " upvoted" if current_user.voted_up_on? post %>
               <% downvote = " downvoted" if current_user.voted_down_on? post %>

              <% end %>
              <div class="text-center post-upvote">
                <%= link_to "", upvote_post_path(post.id), remote:true, 
                class: "fa fa-arrow-up upvote" + upvote , id: "#{post.id}_upvote", title: 'Upvote post', rel: 'tooltip'  %></div>
                <div class = "text-center post-average-score">
                <h3 class=<%= upvote + downvote %>>
                <%= post.get_upvotes.size - post.get_downvotes.size %>
                </h3>
                </div>
              <div class="text-center post-downvote">
                <%= link_to "", downvote_post_path(post.id), remote:true, 
                class: "fa fa-arrow-down downvote" +downvote, id: "#{post.id}_downvote", title: 'Upvote post', rel: 'tooltip'  %>
                </div>

                  <div class="votes_container" style="padding-top: 7px">
     <div class="center">
        <a href="/login" data-remote="true" data-toggle="modal" data-target="#myModal"><img src="/assets/up.png" alt="up"></a>
    </div>
    <div class="vote_container">2</div>
    <div class="center">
        <a href="/login" data-remote="true" data-toggle="modal" data-target="#myModal"><img src="/assets/down.png" alt="down"></a>
    </div>
</div>

app/views/posts/_show_post.html.erb
<div class="starter-template" style="text-align:left">
	<h1 class="header"><a href="/h/musicmakers">musicmakers</a></h1>
	<div style="height:10px"></div>
	<%= render 'layouts/post_new', post: post%>
	<%= render 'comments/comment_box', post: post %>
	<div id="comments_all">
		<div id = "comments-accordion" class="comment-list">
			<ul id ="comments-all">
				<% if post.comments.count > 0 %>
    				<%= render post.comments %>
    			<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/posts/downvote.js.erb
var selector = "#post_scores_<%=@post.id%>"
$(selector).html("<%= j (render partial: 'posts/scores', locals: { post: @post} ) %>")

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'layouts/post_index', posts:@posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% render 'posts/scores', post:@post %>

<%= render 'show_post', post: @post %>

app/views/posts/upvote.js.erb
var selector = "#post_scores_<%=@post.id%>"
$(selector).html("<%= j (render partial: 'posts/scores', locals: { post: @post} ) %>")