config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users
  resources :posts
  get 'home/index'

  root to: "home#index"
  resources :channels
  resources :posts do
    member do
      get 'upvote'
      get 'downvote'
    end
    resources :comments
      member do
        get 'upvote'
        get 'downvote'
      end
  end
 

  resources :comments do
    member do
      get 'upvote'
      get 'downvote'
    end
    resources :comments
    #member do
    #   get 'upvote'
    #   get 'downvote'
    # end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div id="footer" class="footer">© 2017 headcycle | <a href="/help">help</a> | <a href="/contentpolicy">content policy</a> | <a href="/privacypolicy">privacy policy</a> | <a href="/termsofuse">terms of use</a> | <a href="http://www.headcycle.com/rss"><img src="/assets/feed-icon-14x14.png" alt="rss feed"> rss</a></div>

app/views/layouts/_head_nav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top nav-down">
      <div>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="background-color:#ffffff">
            <span class="icon-bar" style="background-color: #000000"></span>
            <span class="icon-bar" style="background-color: #000000"></span>
            <span class="icon-bar" style="background-color: #000000"></span>
          </button>       
           <div class="logo_container"><a href="/" class="logo_container"><img src="/assets/headcycle.png" alt="Headcycle: what are you thinking about?"></a> <a href="/"><span id="site_name">Headcycle</span></a> <a href="/" class="log_line"><span class="log_line_container">what are you thinking about?</span></a></div>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          <li class="hidden-sm hidden-md hidden-lg"><a href="/login" data-remote="true" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-refresh"></span> new post</a></li>
          <li class="hidden-sm hidden-md hidden-lg"><a href="/login" data-remote="true" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-link"></span> new link</a></li>
          <li class="hidden-sm hidden-md hidden-lg"><a href="/headcycles"><span class="glyphicon glyphicon-list"></span> headcycles</a></li>
          <li class="hidden-sm hidden-md hidden-lg"><a href="/search"><span class="glyphicon glyphicon-search"></span> search</a></li>
          <li class="hidden-sm hidden-md hidden-lg"><a href="/wordcloud"><span class="glyphicon glyphicon-cloud"></span> wordcloud</a></li>
          <li><a id="not_logged_in" href="/login" data-remote="true" data-toggle="modal" data-target="#myModal">login</a></li>
            <li><a href="/sign_up" data-remote="true" data-toggle="modal" data-target="#myModal">sign up</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div id="comment_filters_container" class="comment_filters_container"><a href="/">popular</a> · <a href="/new" class="comment_filter">new</a></div>
    <div style="height: 10px"></div>

app/views/layouts/_navig.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Nkata", posts_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><%= link_to "New Channel", new_channel_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Channels <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% Channel.all.each do |single| %>
            <li><%= link_to single.name, channel_path(single) %></li>
          <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
              <% if user_signed_in? %>
        <li>
        <%= link_to("New Post", new_post_path)%>
        </li>
        <li>
        <%= link_to current_user.username, profile_path(current_user.id) %>
        </li>
        <li>
          <%=link_to "Browse Posts", posts_path %>
      </li>
        <li>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to("Login", new_user_session_path)%>
        </li>
        <li>
          <%= link_to("Register", new_user_registration_path)%>
        </li>
      <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_post.html.erb
<div class="single-post">
  <div class="row">
        <div class= "col-md-1 post-score" id = <%= "post_scores_#{post.id}"%> >
          <%= render "posts/scores", post:post %>
        </div>
        <div class="col-md-1 post-thumb">
         <%= get_site_thumbnail post if post.url %>
       </div>

   <div class="col-md-11 post-desc">
    <p class = "post-title"> <h2><%=post.title%> <span class = "post-url">(<%=post.url%>)</span></h2></p>
    <p class="post-poster"><h4>
      submitted by <%= link_to post.user.username, profile_path(post.user.id) %>
      <%=" #{time_ago_in_words post.created_at} ago to " %>
      <%= link_to post.channel.name, channel_path(post.channel.id) %></h4>
    </p>
    <div class="row">
      <div class="col-md-2">
        <p class="post-comments"><h5>
          <%= link_to "#{post.comments.size} comments", post_path(post.id) %></h5>
        </p>
      </div>
      <% if user_signed_in? && (current_user.id == post.user.id) %>


      <div class="col-md-1">
       <p class="post-edit"><h5>
        <%=  link_to 'Edit', edit_post_path(post)  %></h5>
      </p>
    </div>
    <div class="col-md-1">
     <p class="post-delete"><h5>
      <%=  link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }   %></h5>
    </p>
  </div>
  <% end %>
</div>


</div>
</div>
</div>

app/views/layouts/_post_index.html.erb
<% posts.each do |post| %>
    <%= render 'layouts/post_new', post:post %>
<% end %>

app/views/layouts/_post_new.html.erb
<div class="comments_container">

<div class="comment_table">
  <div class="comment_row">
    <div class="comment_cell">
        <div style="margin-right:20px;padding-top: 6px">
            <a class="comments_title_container" href="https://youtu.be/HQoOfiLz1G4" target="w_1490527906"><img src="https://s3.amazonaws.com/headcycle/6c56927e1167" alt="Sound City Official Trailer - YouTube"></a>
            <%= link_to model_path(@model) %>
        </div>
    </div>
    <div class="comment_cell">
        <a class="comments_title_container" href="https://youtu.be/HQoOfiLz1G4" target="w_1490527906">Sound City Official Trailer - YouTube <span class="glyphicon glyphicon-link" style="font-size: 20px"></span></a> <span class="site_container">(youtu.be)</span>
        <div class="comments_info_container">
            submitted by <a href="/user/jimi14" style="font-weight: bold">jimi14</a> 2 days ago to <a href="/h/music" style="font-weight: bold">/h/music</a></div>
            <div class="comments_count_container"><a class="comments_count_color" href="#">0 comments</a> · <a href="#">initial post</a> · <a href="#" onclick="$('#share_25a6d979d28c').slideToggle();return false">share</a></div>
            <div id="share_25a6d979d28c" class="share" style="font-size:20px;padding:10px;display:none;background-color: #f6f6f6;border:2px dashed #cccccc">
                <div style="text-align:right"><a href="#" onclick="$('#share_25a6d979d28c').slideToggle();return false" style="color:#cccccc"><span class="glyphicon glyphicon-remove"></span></a></div>
                Share with: <a style="display:inline-block;" data-toggle="tooltip" title="" href="#" target="_blank" data-original-title="Share to facebook"><img src="/facebook_48.png" width="48" alt="share on facebook"></a>&nbsp;
                <a style="display:inline-block;" data-toggle="tooltip" title="" href="#" target="_blank" data-original-title="Share to twitter"><img src="/twitter_48.png" width="48" alt="share on twitter"></a>&nbsp;
                <a style="display:inline-block;" data-toggle="tooltip" title="" href="#" target="_blank" data-original-title="Share to google+"><img src="/google-plus_48.png" width="48" alt="share on google+"></a>&nbsp;
                <a href="/login" style="display:inline-block;" data-remote="true" data-target="#myModal" data-toggle="modal" title="Share via email"><img src="/email2_48.png" width="48" alt="share via email"></a>
            </div>
        </div>
    </div>	
</div>
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="hidden-xs">
        	<div style="height:10px;margin-top:15px"></div>
	<form action="/search" id="search_form" class="form-inline">
		<input onfocus="javascript: $('#limit_search').show('slow')" type="text" name="q" style="width:70%;" class="form-control" placeholder="search">
		<button type="submit" class="btn btn-primary" onclick="setSearchFormAction()">
	 		<i class="glyphicon glyphicon-search"></i>
		</button>
	</form>
				<div class="sidebar_links_container" style="margin-top:15px">
				<a href="/login" data-remote="true" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-refresh"></span> New Post</a>
				</div>
				<div class="sidebar_links_container">
				<a href="/login" data-remote="true" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon glyphicon-link"></span> New Link</a>
				</div>
	<div class="sidebar_links_container"><a href="/headcycles"><span class="glyphicon glyphicon-th-list"></span> Headcycles</a></div>
	<div class="sidebar_links_container">
		<a href="/login" data-remote="true" data-toggle="modal" data-target="#myModal">
	 <span class="glyphicon glyphicon-repeat"></span> Create a Headcycle</a>
	</div>
	<div class="sidebar_links_container"><a href="/wordcloud"><span class="glyphicon glyphicon-cloud"></span> Wordcloud</a></div>
<div class="sidebar_links_container" style="width:100%"><a href="javascript: void(0)" onclick="self.location = '/?siteguide=true&amp;cb=1490738365'" data-no-turbolink="true"><span class="glyphicon glyphicon-road" style="color: #ffb6c1"></span> Headcycle Tour</a></div>

      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nkata</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  		<%= render "layouts/navig" %>

  		<div class = "container-fluid">
	<div class = "site">
	       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

		<%= yield %>
	</div>
</div>
    
  </body>
</html>

app/views/layouts/head.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nkata</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  		<%= render "layouts/head_nav" %>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    

      <div class='da-body'>
        <%= render "layouts/sidebar" %>
        
        <%= yield %>
        <%= render "layouts/footer" %>
      </div>


	    <script type="text/javascript">
$('.nav a').on('click', function(){
$(".navbar-collapse").css("height", "1px");
$(".navbar-collapse").removeClass("in");
$(".navbar-collapse").addClass("collapse");
});
$(function () {
    $('[data-toggle="tooltip"]').tooltip();
});
</script>   
  </body>
</html>